# Generated by Django 3.1.5 on 2021-02-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desa', models.CharField(max_length=30)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.kecamatan')),
            ],
        ),
    ]
