# Generated by Django 3.1.7 on 2021-03-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spptbaru',
            name='transaksi',
            field=models.CharField(blank=True, choices=[('Jual Beli', 'Jual Beli'), ('Hibah', 'Hibah'), ('Waris', 'Waris'), ('Penghapusan', 'Penghapusan'), ('AJB', 'AJB'), ('Sertifikat', 'Sertifikat'), ('Dll', 'Dll')], max_length=20),
        ),
    ]
