# Generated by Django 3.1.5 on 2021-02-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20210201_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desa',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.kecamatan'),
        ),
    ]
