# Generated by Django 3.1.5 on 2021-02-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210201_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pendaftaran', models.DateField()),
                ('no_pelayanan', models.CharField(blank=True, default=0, max_length=11, null=True, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('mutasi', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField()),
                ('keterangan', models.CharField(choices=[('PROSES', 'PROSES'), ('SELESAI', 'SELESAI')], max_length=20)),
                ('tanggal_selesai', models.DateField()),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.desa')),
                ('kecamatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.kecamatan')),
            ],
        ),
    ]
