# Generated by Django 3.1.5 on 2021-02-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_pendaftaran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desa',
            old_name='desa',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='kecamatan',
            old_name='kecamatan',
            new_name='nama',
        ),
    ]
