# Generated by Django 3.1.5 on 2021-02-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20210206_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='desa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.desa'),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.kecamatan'),
        ),
    ]
