# Generated by Django 3.1.5 on 2021-02-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20210216_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPPTLama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sppt_lama', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('nama_wp_lama', models.CharField(max_length=100)),
                ('tarif_lama', models.DecimalField(decimal_places=4, max_digits=19)),
                ('no_pelayanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.pendaftaran')),
            ],
        ),
    ]
