# Generated by Django 3.1.5 on 2021-02-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_spptlama'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPPTBaru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sppt_baru', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('nama_wp_baru', models.CharField(max_length=100)),
                ('tarif_lama', models.DecimalField(decimal_places=4, max_digits=19)),
                ('keterangan', models.CharField(choices=[('TETAP', 'TETAP'), ('BARU', 'BARU'), ('NAIK', 'NAIK'), ('TURUN', 'TURUN')], max_length=20)),
                ('transaksi', models.CharField(max_length=20)),
                ('luas_tanah', models.IntegerField()),
                ('luas_bangunan', models.IntegerField()),
                ('sppt_lama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.spptlama')),
            ],
        ),
    ]
