# Generated by Django 3.1.5 on 2021-02-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_spptbaru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spptbaru',
            old_name='tarif_lama',
            new_name='tarif_baru',
        ),
    ]
