# Generated by Django 3.1.5 on 2021-02-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20210216_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spptbaru',
            name='keterangan',
            field=models.CharField(blank=True, choices=[('TETAP', 'TETAP'), ('BARU', 'BARU'), ('NAIK', 'NAIK'), ('TURUN', 'TURUN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spptbaru',
            name='luas_bangunan',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spptbaru',
            name='luas_tanah',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spptbaru',
            name='tarif_baru',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='spptbaru',
            name='transaksi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='spptlama',
            name='tarif_lama',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19),
        ),
    ]
