# Generated by Django 3.1.5 on 2021-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20210219_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spptbaru',
            name='luas_bangunan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spptbaru',
            name='luas_tanah',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
