# Generated by Django 3.1.5 on 2021-02-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20210219_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spptbaru',
            name='no_sppt_baru',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='spptlama',
            name='no_sppt_lama',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
