# Generated by Django 3.1.7 on 2021-02-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20210224_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spptbaru',
            name='sppt_lama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.spptlama'),
        ),
        migrations.AlterField(
            model_name='spptlama',
            name='no_pelayanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.pendaftaran'),
        ),
    ]
